[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tedbuy"
version = "0.0.1"
authors = [
  { name="ted chang", email="htchang@us.ibm.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/tedhtchang/tedbuy"
Issues = "https://github.com/tedhtchang/tedbuy/issues"
