[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool.poetry]
authors = ["Lukas Karlsson <karlsson@broadinstitute.org>"]
description = "BITS GitHub Package for Python"
exclude = [
    "**/*.pyc",
    "**/*.pyi",
]
homepage = "https://github.com/broadinstitute/bits-github.git"
keywords = ["bits", "github"]
license = "BSD-3-Clause"
name = "bits-github"
packages = [
    { include = "bits" },
]
readme = "README.md"
repository = "https://github.com/broadinstitute/bits-github.git"
version = "1.4.1"

[tool.poetry.dependencies]
python = "^3.9"  # Compatible python versions must be declared here

bits-google = "^1.13.8"
google-cloud-datastore = "^2.19.0"
google-cloud-firestore = "^2.15.0"
python-dateutil = "^2.9.0.post0"
pytz = "*"
testtools = "^2.7.1"
twine = "^5.0.0"
wheel = "^0.43.0"

[tool.ruff]
line-length = 120

[tool.ruff.format]
# Prefer double quotes over single quotes.
quote-style = "double"

[tool.ruff.lint]
fixable = ["ALL"]
ignore = ["D104"]
select = [
  "D",   # pydocstyle
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort
  "N",   # pep8-naming
  "PL",  # Pylint
  "UP",  # pyupgrade
]

[tool.ruff.lint.pydocstyle]
convention = "google"
