[project]
name = "par-run"
version = "0.1.2"
description = "Parallel command runner"
license = "MIT"
authors = [
    { name = "Naz Quadri", email = "naz.quadri@gmail.com" }
]
dependencies = [
    "rich>=13.0.0",
    "typer>=0.9.0",
    "pydantic>=2.0.0",
]
readme = "README.md"
requires-python = ">= 3.9"

[project.optional-dependencies]
web = [
    "fastapi>=0.100.0",
    "uvicorn[standard]>=0.29.0",
    "jinja2>=3.0.0",
    "psutil>=5.9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "bump-my-version>=0.19.3",
    "httpx>=0.27.0",
    "mypy>=1.9.0",
    "pytest>=8.1.1",
    "pytest-asyncio>=0.23.6",
    "pytest-benchmark>=4.0.0",
    "pytest-cov>=5.0.0",
    "pytest-mock>=3.14.0",
    "pytest-random-order>=1.1.1",
    "ruff>=0.3.4",
    "twine>=5.0.0",
    "types-toml>=0.10.8.20240310",
    "types-psutil>=5.9.5.20240316",
]

[project.scripts]
"par-run" = "par_run.cli:cli_app"


[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = [
    "src/par_run",
    "static",
    "templates",
]

[tool.bumpversion]
current_version = "0.1.2"
commit = true
tag = true
tag_name = "{new_version}"
tag_message = "Version {new_version}"
message = "Bump version: {current_version} â†’ {new_version}"
allow_dirty = true
parse = """(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"""
serialize = [
    "{major}.{minor}.{patch}"
]

[[tool.bumpversion.files]]
filename = "src/par_run/__init__.py"

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py39"

[tool.pytest.ini_options]
addopts = "--cov src --cov-report html:.reports/html --cov-report term --random-order -p no:warnings -v"
minversion = "8.0"
pythonpath = ["src", "py_tests"]
testpaths = "py_tests"
pythonfiles = "test_*.py"
