[tool.poetry]
name = "google-injector"
version = "1.0.3"
description = ""
authors = ["Antoni Oktha Fernandes <37358597+DesKaOne@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "google_injector"}]

[tool.poetry.dependencies]
python = "^3.8"
http-injector = "^1.0.1"
pycryptodomex = "^3.20.0"
sqlalchemy = "^2.0.29"
python-dotenv = "^1.0.1"
oauth2client = "^4.1.3"
python-jwt = "^4.1.0"
sqlalchemy-utils = "^0.41.2"
gcloud = "^0.18.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
