



[build-system]
requires = [ "setuptools>=61.0",]
build-backend = "setuptools.build_meta"

[project]
name = "apoplast"
version = "1.1.1"
dependencies = [ 
	"volts", 
	"ships", 
	"sphene",
	
	"pymongo",
	"pydash",
	"rich", 
	"tinydb",
	"numpy", 
	
]
description = "The search for an abundant panacea of vivaciously invigorating utopian vegan absorbables."
readme = "readme.md"

[project.license]
text = "GPL 3.0 + vegan"

[project.urls]
GitLab = "https://gitlab.com/reptilian_climates/modules_series_4/apoplast"

[tool.setuptools.package-data]
"*" = [ "*.HTML", "*.html", "*.JSON", "*.json",]

[tool.setuptools.packages.find]
where = [ "structures/modules",]
