[tool.poetry]
name = "reperiods"
version = "1.0.1"
description = "A set of tools to find Representative Periods."
authors = ["RobinsonBeaucour <robinson.beaucour@outlook.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pulp = "^2.8.0"
scikit-learn-extra = "^0.3.0"
plotly = "^5.20.0"
scikit-learn = "^1.4.1.post1"
pandas = "^2.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[tool.poetry.group.doc]
optional = true

[tool.poetry.group.doc.dependencies]
sphinx = "^7.2.6"
nbsphinx = "^0.9.3"
sphinx-rtd-theme = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
