[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "querypanda"
version = "0.2.2"
description = "From SQL queries to pandas DataFrames: QueryPanda makes it easy to retrieve, aggregate, and save data from PostgreSQL, enhancing data analysis and machine learning projects."
authors = [{name = "Shashank Goud", email = "shashaankgoud@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
urls.Homepage = "https://github.com/Shazankk/QueryPanda"
urls.Repository = "https://github.com/Shazankk/QueryPanda"

dependencies = [
    "pandas>=1.2.0",
    "psycopg2-binary>=2.8.6",
    "openpyxl>=3.0.5",
]

[project.optional-dependencies]
# Specify any optional dependencies here; rename "extras" if you have specific sets of optional dependencies
# Example:
# dev = ["pytest", "flake8"]

[tool.setuptools]
packages = ["querypanda"]
package-dir = {"" = "src"}  # Adjust if your package is located in a different directory
