[tool.poetry]
name = "modelmarket"
version = "0.1.76"
description = "The official client for the ModelMarket API"
authors = ["modelmarket <info@modelmarket.io>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/modelmarket-io/modelmarket-sdk"
classifiers = [
    "Programming Language :: Python :: 3.7"
]

[tool.poetry.dependencies]
python = "^3.7"
requests = ">=2"
pandas = ">=1.2"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
