[tool.poetry]
name = "uprock-sdk"
version = "0.1.11"
description = ""
authors = ["Aleksey Dalekin <adalekin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
html-sanitizer = "^2.3.1"
httpx = "^0.27.0"
jinja2 = "^3.1.3"
pydantic = ">=2.4.1,<2.6"
pydantic-settings = "^2.2.1"
python = "^3.10"

[tool.poetry.dev-dependencies]
mypy = "^1.1.1"
pre-commit = "^3.1.0"
pytest = "^8.1.1"
ruff = "^0.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
