[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "calculator-papartynas"
authors = [{name = "Martynas PetkeviÄius", email = "mpetkevicius@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
requires-python = ">=3.11"
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/TuringCollegeSubmissions/mapetke-DWWP.1.5"
