[tool.poetry]
name = "awesom-sitemap-parser"
version = "0.1.0"
description = ""
authors = ["Artem Chekunov <artem.v.chekunov@gmail.com>"]
license = "GPL3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"
python-dateutil = "^2.9.0.post0"

[tool.poetry.group.dev.dependencies]
ipython = "^8.22.2"
requests-mock = "^1.12.0"
setuptools = "^69.2.0"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
addopts = "-v"
